services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 2s
      retries: 5

  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
